name: Run tests

on: [push, pull_request]

jobs:
  run_tests:
    strategy:
      matrix:
        include:
          - nvim_tag: v0.7.0

    name: Run tests
    runs-on: ubuntu-latest
    env:
      NVIM_TAG: ${{ matrix.nvim_tag }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Neovim and dependencies
        run: |
          bash ./.github/workflows/install_nvim.sh

      - name: Install tree-sitter CLI
        run: |
          npm install -g tree-sitter-cli

      - name: Ensure TS parsers installed
        run: |
          nvim --headless -c "TSInstallSync all" -c "q"

      - name: Run tests
        run: |
          bash ./run_tests.sh
